version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: rapidoja_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: rapidoja_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - rapidoja_network

volumes:
  mysql_data:

networks:
  rapidoja_network:
    driver: bridge
